function createData(name, details, suitable, fee, more) {
    return { name, details, suitable, fee, more };
}

export const row = [
    createData('Students Interactive Society', 'The main student body within SLIIT, comprising student representatives of the Departmental societies in Information Technology, Engineering, and Business Management. The patrons of the society are the Chancellor and Vise Chancellor of SLIIT. SIS together with the respective student communities, organize various events, maintains decorum and adheres to rules, upholding the good name of the institute.','Any 4th year students who are interested can apply','No fee to join','https://www.sliit.lk/student-life/clubs-societies/students-interactive-society/'),
    createData('Sports Council', 'Promotes sports and recreational activities. At SLIIT, students engage in a wide range of sports including cricket, rugby, volleyball, tennis, table tennis, badminton, chess, carom and karate. The Malabe campus has excellent indoor and outdoor sports facilities. These include a large playground, a tennis court, a basketball court, indoor table tennis, carom and a well- equipped gymnasium','Students who participate in many sports and want to manager the sports in SLIIT can join','No Fee to join','https://www.sliit.lk/student-life/clubs-societies/sports-council/'),
    createData('Faculty of computing student community (FCSC)','Aims at enhancing the knowledge of IT students and accustom them to the ever-changing IT industry. This is done through activities such as workshops and guest lectures by leading IT Professionals in the industry, enabling better student interaction and knowledge-sharing.','Students are form 3rd and 4th year of Software Engineering can join','No fee to join','https://www.sliit.lk/student-life/clubs-societies/faculty-societies/fcsc/'),
    createData('Faculty of engineering student community (FESC)','Considered the main student community of the Faculty of Engineering, functioning under the guidance of the Student Interactive Society (SIS). FESC mainly focuses on the academic problems and the difficulties of engineering students and works together with the senior staff of the faculty and the community for solutions.','Students are form 3rd and 4th year of Software Engineering can join','Noo fee to join','https://www.sliit.lk/student-life/clubs-societies/faculty-societies/'),
    createData('SLIIT Business School Student Community (SBSSC)','Formed under the main student body, The student Interactive Society (SIS), comprises the undergraduates of the Business Management stream. The committee acts as the student representative, facilitating necessary programmes along with managing the SLIIT Business School.','','No fee to join','https://www.sliit.lk/student-life/clubs-societies/faculty-societies/'),
    createData('Faculty of Humanities and Sciences Student Community (FHSSC)','Faculty of Humanities and Sciences is a multidisciplinary Faculty and FHSSC is the student body that comprises of students from all the disciplines mainly, Natural Science & Education, Law, Psychology, Nursing and Mathematics. The FHSSC focuses on enhancing student satisfaction in terms of academic and non-academic issues and enriching the overall student experience at SLIIT. FHSSC collaborates and seek guidance continuously from the Senior Faculty members, to extend their support for the student body effectively.','','','https://www.sliit.lk/student-life/clubs-societies/faculty-societies/faculty-of-humanities-sciences-student-community-fhssc/'),
    createData('ISACA in SLIIT','ISACA SLIIT student chapter is to promote the career in assurance and consult audit in cyber security sides. To provide the career work we do some workshops and meetups to help the students to get success. ISACA SLIIT Student Chapter is the third ISACA Student Chapter under the ISACA Sri Lanaka Chapter, which work with the aim of encouraging education beyond the university students’ capability to learn and to connect the supportive professionals in the industry.','Best suitable for Cyber Security students','Annual membership fee','https://www.sliit.lk/student-life/clubs-societies/other-societies/isaca-in-sliit/'),
    createData('Rotaract Club','A service club established for SLIIT students under ‘Rotary International’. The sponsorship by local Rotary Club/s is mentored by the parent club in Battaramulla.','Membership is open to all SLIIT students and aims to develop professional and leadership skills, emphasizing on respect for rights of others, promoting ethical standards and the dignity of all useful occupations.', 'No fee to join','https://rotaractsliit.com/'),
    createData('The Gavel Club','The Gavel Club has thrived in the guidance and support of the SLIIT Toastmasters Club, as well as other academic staff. As a communications and leadership programme modeled after Toastmasters International, The Gavel club is a way of providing the Toastmasters experience to groups who may be eligible for regular membership.','Anyone who is interested to improve their spoken English','Membership fee','https://sliitgavelclub.wordpress.com/'),
    createData('SLIIT Gaming Community','Formed in 2013, by a group of young, dynamic individuals with a passion for digital games including game designing and developing. A multipurpose group to create opportunities amongst those interested in this particular field. The community mainly intends to teach the fundamentals of game designing and development, providing resources and instructions to those willing to embark on creating or designing games and game testing.','Students who are interested in the related field','No fee to join','https://sliit-gc.github.io/SLIIT-GC-Web/'),
    createData('SLIIT AIESEC','We enable young people to develop their leadership potential through learning from practical experiences in challenging environments. We do this through cross-cultural exchanges.','Anyone who is interested', 'Membership fee','https://lk.linkedin.com/company/aiesecinsliit'),
    createData('SLIIT LEO Club','Leo Club of SLIIT (SLIIT Leos) is one of the best clubs in Leo District 306 C1 Sri Lanka and Leo Multiple District 306, which titled “The Most Outstanding New University Leo Club of Sri Lanka, Leostic Year 2017/2018”.','Any on who is interested to interact with everyone','No fee to join','https://sliitleo.org/'),
    createData('SLIIT Faculty Of Computing Media Unit','Faculty of Computing Media Unit is a non-profit organization which sole aspect is to engage in media coverage in every special occasion inside Sri Lanka Institute of Information Technology.','Computing faculty students who are interested in photography, editing , etc','No fee to join','https://lk.linkedin.com/company/sliit-fcmu'),
    createData('SLIIT Faculty Of Engineering Media Unit','','Any on who is interested to interact with everyone','Faculty of Engineering Media Unit is a non-profit organization which sole aspect is to engage in media coverage in every special occasion inside Sri Lanka Institute of Information Technology.','Engineering faculty students who are interested in photography, editing , etc','No fee to join','https://lk.linkedin.com/company/sliitfemc'),
    createData('IEEE Student Branch of SLIIT','IEEE Student Branch of SLIIT has been one of the prominent student branches functioning in Sri Lanka. The branch has pioneered diverse projects including technical, community service etc','Anyone who is interested','Membership fee','https://www.facebook.com/ieee.sliit/'),
    createData('SLIIT Engineering Research and Innovation Club','Engineering Research and Innovation Club (ERIC) at SLIIT is a student led organization established to connect, collaborate, organize and socialize students and excels innovative and creative thinking within students. The club organizes workshops, events, competitions to provide students with hands on learning experience. Club focuses to enhance interaction among industry, society and university representatives with a motto of “Research and Innovation for social development”.','Engineering faculty students','No fee to join','https://www.facebook.com/SLIITERIC/'),
    createData('Art Circle SLIIT','Dancing , Drama and Singing for Life', 'Anyone who is interested','No fee to join','https://www.facebook.com/SLIITArtCircle/'),
    createData('SLIIT Drama Society','Club where you can learn a lot about drama','Anyone who is interested','No fee to join',''),
]