function createData(name, semester, fee, eligibility, payment, enroll, faculty) {
    return { name, semester, fee, eligibility, payment, enroll, faculty };
}

// export const computing = [
//     createData('BSc. Information Technology (Specialized in Information Technology)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BSc. Information Technology (Specialized in Computer System & Network Engineering)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT', 'Rs.240,000.00', 'February/ June/ September'),
//     createData('BSc. Information Technology (Specialized in Software ENgineering)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT. To progress from the second year to the third year of the program, a student must pass all the modules up to the second year and maintain a minimum CGPA of 2.7.', 'Rs 215,000 per semester for the first two years and Rs. 240,000 per semester for the final two years', 'February/ June/ September'),
//     createData('BSc. Information Technology (Specialized in Information System Engineering)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT.', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BSc. Information Technology (Specialized in Cyber Security)', 8, '6 months', 'Passes in three subjects (in any stream) at the G.C.E (Advanced Level) examination (Sri Lankan/London) in one and the same sitting and a pass at the Aptitude Test conducted by SLIIT. To progress from the first year to the second year of the specialization, a student must meet the minimum GPA requirement specified by the Faculty.', ' Rs 215,000 per semester for the first year and Rs. 240,000 per semester for the final three years.', 'February/ June/ September'),
//     createData('BSc. Information Technology (Specialized in Interactive Media)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination(Sri Lankan/London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT. To progress from the second year to the third year of the program, a student must pass a selection interview.', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BSc. Information Technology (Specialized in Data Science)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT. To progress from the second year to the third year of the program, a student must pass all the modules up to the second year and maintain a minimum CGPA of 2.7', 'Rs 215,000 per semester for the first two years and Rs. 240,000 per semester for the final two years', 'February/ June/ September'),
// ];

// export const engineering = [
//     createData('BSc. Engineering (Hons) in Civil Engineering', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.330,000.00', 'February/ September'),
//     createData('BSc. Engineering (Hons) in Electrical & Electronic Engineering', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.330,000.00', 'February/ September'),
//     createData('BSc. Engineering (Hons) in Mechanical Engineering', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ September'),
//     createData('BSc. Engineering (Hons) in Mechanical Engineering (Mechatronics specialization ', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.330,000.00', 'February/ September'),
//     createData('BSc. Engineering (Hons) in Material Engineering', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.330,000.00', 'February/ September'),
//     createData('BSc. (Hons) Degree in Quantity Surveying', 6, '6 months', 'Minimum of 3 "S" passes in Physical Science stream & a "C" pass for O/L English.Or Minimum of 3 "S" passes in Biology/Commerce/ Engineering Technology Streams & a “B” pass for O/L Mathematics & a “C” pass for O/L English. Cambridge/Edexcel A/Ls : Minimum of 3 "D" passes in Mathematics stream (Subjects equivalent to local Physical Science Stream) & a "C" pass for O/L English. Or Minimum of 3 "D" passes in Biology/Commerce Streams & a “B” pass for O/L Mathematics & a “C” pass for O/L English.', 'Rs.215,000.00', 'February/ September'),
// ];

// export const business = [
//     createData('BBA (Hons) Specializing in Accounting & Finance', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BBA (Hons) Specializing in Business Analytics', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', ' Rs 215,000 per semester for the first two years and Rs. 240,000 per semester for the final two years.', 'February/ June/ September'),
//     createData('BBA (Hons) Specializing in Human Capital Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BBA (Hons) Specializing in Marketing Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BBA (Hons) Specializing in Logistic & Supply Chain Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BBA (Hons) Specializing in Business Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BBA (Hons) Specializing in Management Information Systems', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('BBA (Hons) Specializing in Quality Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
//     createData('Bachelor of Business Administration (Hons)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September'),
// ];

// export const humanity = [
//     createData('Higher Diploma in Nursing', 6, '6 months', 'Passes in three subjects at the G.C.E. Advanced Level examinations (Edexcel / Cambridge / Local or equivalent) obtained at one and the same sitting in the Science stream. A pass in the aptitude test conducted by SLIIT. Successful passing at an Interview conducted by a Board of Academic Panel', 'Rs.215,000.00', 'February/ September'),
//     createData('B.Ed (Hons) in Biological Sciences', 8, '6 months', 'Pass in three subjects at the G.C.E Advanced Level examinations (Local or London or equivalent) obtained at one and the same sitting in the Science stream and a pass in the aptitude test conducted by the Institute.', 'Rs.170,000.00', 'February/ September'),
//     createData('B.Ed (Hons) in English', 8, '6 months', 'Minimum of three (03) “S’’ passes in any subject stream (‘English’ should be one of the main three subjects) in one and the same sitting at the GCE (Advance Level) Examination (Sri Lanka/London) and the same sitting, and a pass at the Aptitude Test conducted by SLIIT', 'Rs.170,000.00', 'February/ September'),
//     createData('B.Ed (Hons) in Physical Sciences', 8, '6 months', 'Passes in three subjects including Mathematics (Combined Mathematics or Higher Mathematics) and Physics at G.C.E (Advanced Level) Examination in one and the same sitting and a pass in the Aptitude Test conducted by the Institute.', 'Rs.170,000.00', 'February/ September'),
//     createData('B.Ed (Hons) in Biotechnology', 8, '6 months', '- Three ‘S’ passes at G.C.E. Advanced Level examinations covering Biology & Chemistry OR three ‘D’ passes at Edexcel or Cambridge Advanced Level examinations covering Biology & Chemistry with obtained at one and the same sitting in the Science stream.- A Pass in the Aptitude Test conducted by the Institute.', 'Rs.250,000.00', 'February/ September'),
//     createData('B.Ed (Hons) in Financial Mathematics and Applied Statistics', 8, '6 months', ' Passes in three subjects in Physical Science stream at local G.C.E. Advanced Level Examination or equivalent qualification of London/Cambridge A/L examination in one and the same sitting and a pass in the Aptitude Test conducted by the Institute.', 'Rs.215,000.00', 'February/ September'),
//     createData('LLB (Hons) Law', 6, '6 months', '2 Credit Passes and 1 simple pass in any subject stream at GCE (Advanced Level) Examination, Sri Lanka or London in one and the same sitting with a Credit (C) pass for English at the GCE (Ordinary Level) examination and Pass at the aptitude test conducted by SLIIT and the interview conducted by the School of Law, SLIIT', 'Rs.215,000.00', 'February/ September'),
//     createData('BSc (Hons) Psychology', 6, '6 months', 'Eligibility for the programme are as follows: GCE Advance Level (Local) - 3 passes in any stream. GCE Advance Level (Edexcel / Cambridge) - 3 D passes in any stream. Final Year Entry to the BSc (Hons) Psychology Higher Diploma/Higher national Diploma in Psychology', 'Rs.215,000.00', 'February/ July'),
//     createData('BSc (Hons) Nursing (International)', 4, '6 months', 'Eligibility for the programme are as follows: Criteria for admission Overseas qualifications Candidates must be able to satisfy the programme team that they meet the entry requirements of the programme: Students must demonstrate a proficiency in English with either a credit pass for English at the GCE (Ordinary level) examination - OR the standard equivalent to IELTS 6. The candidate must be employed as a nurse and must have at least 1 year\'s post-registration experience and a Sri Lankan Diploma of nursing.', 'Rs.215,000.00', 'February/ July'),
// ];

// export const architect = [
//     createData('BSc. (Hons) in Architecture', 6, '6 months', 'GCE Advanced Level (Local) - 3 passes in any stream. (Preferably in the Biology, Mathematics or Engineering Technology) GCE Advanced Level ((Ed-excel/Cambridge) – 3 passes and meet the required 5 points Compulsory “C”passes in Mathematics and English at the GCE Ordinary Level (Local / London) Successful candidates will be selected through an aptitude test (followed by an interview if required) conducted by the SLIIT School of Architecture at the SLIIT Malabe Campus.', 'Rs.215,000.00', 'February/ June'),
//     createData('BA (Hons) Interior Design', 6, '6 months', 'GCE advanced level examination (local) or London advanced level examinations 3 passes in any stream. Lateral Entry– Foundation Course (1 Year) approved by LJMU with GCE Ordinary Level examinations (local) 6 passes in any stream with minimum C passes for both Math\'s and English Successful candidates will be selected through an aptitude test (followed by an interview if required) conducted by the School of Architecture at SLIIT.', 'Rs.240,000.00', 'February/ June'),
// ];

// export const culinary = [
//     createData('Advance Diploma in Hospitality Management', 4, '6 months', 'Sri Lankan students: 5 Ordinary Level Passes including English language, International Students: 5 passes in the 10th standard including English language.', '<a href="https://www.cahm.lk/programmes/degree-diploma-programmes/hospitality-management/">Fees Details</a>', 'February/ June/ September'),
//     createData('Commercial Cookery', 3, '6 months', 'Sri Lankan students: 5 Ordinary Level Passes including English language, International Students: 5 passes in the 10th standard including English language.', '<a href="https://www.cahm.lk/programmes/degree-diploma-programmes/commercial-cookery/">Fees Details</a>', 'August/ December'),
//     createData('Certificate in Patisserie', 4, '6 months', '5 Passes in O/Level (Local/London/Cambridge)including English', 'COntact SLIIT', 'February/ July'),
//     createData('Advance Diploma in Travel and Tourism Management', 3, '6 months', '5 Passes in O/Level (Local/London/Cambridge)including English', 'Contact SLIIT', 'February/ July'),
//     createData('Diploma in Event Management', 8, '6 months', 'Sri Lankan students: 5 Ordinary Level Passes including English language, International Students: 5 passes in the 10th standard including English language.', '<a href="https://www.cahm.lk/programmes/event-management/">Fees Details</a>', 'August/ December'),
// ];

// export const master = [
//     createData('Postgraduate Diploma in Education', 4, '4.5 months', ' To have degree obtained from a recognized university or a degree awarding institution recognized by the Ministry of Education or To have a Certificate of National Vocational Qualification level 7 ', 'Rs.110,000.00', 'December'),
//     createData('MSc in Information Technology', 4, '6 months', 'A Bachelor of Science Honors Degree in Information Technology of the Sri Lanka Institute of Information Technology (SLIIT)./ A Bachelor of Science Honors Degree in Computer Science/ Information Technology/Software Engineering from a recognized University in Sri Lanka./ A Bachelor’s degree in a relevant field from a recognized University/Institute as approved by the SLIIT with relevant experience, where necessary / Membership of a recognized professional institute in a relevant field as approved by SLIIT with relevant experience, where necessary.', 'Rs.375,000.00', 'June'),
//     createData('MSc in information Management', 4, '6 months', 'A Bachelor of Science Degree in any field from a recognized University in Sri Lanka/ Any Bachelor’s Degree in a relevant field from a recognized University or institute as approved by SLIIT/ Membership of a recognized professional institute in a relevant field as approved by the SLIIT with relevant field experience, where necessary. And One year working experience at Managerial Level', 'Rs.375,000.00', 'June'),
//     createData('MSc in Information Systems', 4, '6 months', 'A Bachelor of Science Honors Degree in Information Technology of the SLIIT./ A Bachelor of Science Honors Degree in Computer Science/ Information Technology/Software Engineering from a recognized University in Sri Lanka./ A Bachelor’s degree in a relevant field from a recognized University/Institute as approved by the SLIIT with relevant experience, where necessary/ Membership of a recognized professional institute in a relevant field as approved by SLIIT with relevant experience, where necessary', 'Rs.375,000.00', 'June'),
//     createData('MSc in Information Technology - Cyber Security', 4, '6 months', 'A Bachelor of Science Honors Degree in Information Technology of the SLIIT/ A Bachelor of Science Honors Degree in Computer Science/ Information Technology/Software Engineering from a recognized University in Sri Lanka/ A Bachelor’s degree in a relevant field from a recognized University/Institute as approved by the SLIIT with relevant experience, where necessary./ Membership of a recognized professional institute in a relevant field as approved by SLIIT with relevant experience, where necessary', 'Rs.395,000.00', 'June'),
//     createData('MSc in Information technology - Enterprise Application Development', 4, '6 months', 'A Bachelor of Science Honors Degree in Information Technology of the SLIIT/ A Bachelor of Science Honors Degree in Computer Science/ Information Technology/Software Engineering from a recognized University in Sri Lanka/ A Bachelor’s degree in a relevant field from a recognized University/Institute as approved by the SLIIT with relevant experience, where necessary./ Membership of a recognized professional institute in a relevant field as approved by SLIIT with relevant experience, where necessary', 'Rs.395,000.00', 'June'),
//     createData('Master of Business Administration', 4, '6 months', 'The applicants with a Bachelor’s Degree in Business Administration or related area from a recognized university are eligible to apply for the course. Those with a Bachelor’s Degree in other subject areas need to have one year’s post qualifying experience. Applicants with professional qualifications and two year’s post-qualifying experience approved by SLIIT are also eligible to apply.', 'Rs.500,000.00', 'June'),
//     createData('Master of Philosophy (MPhil)', '4/ 6', '6 months', 'A Bachelor’s Honours Degree of SLQF level 6 with a minimum of 15 credits in a related field/ A Bachelor’s degree of SLQF level 5 with a minimum GPA of 3 on a scale of 0-4 and after the successful completion of 30 credits equivalent to SLQF 6 in a related field./ A qualification of SLQF level 7, i.e. a Postgraduate Certificate or above in a related field./ Completion of NVQF level 7 with a minimum GPA of 3 in a scale of 0-4 and the successful completion of 30 credit equivalent to SLQF level 6 or above in a related field as approved by the institute', 'Rs.200,000.00', 'All year'),
//     createData('Doctor of Philosophy (PhD) ', '6/ 10', '6 months', 'A Master of Philosophy Degree from a recognized institution acceptable to the Senate (I.I)/ A Bachelor’s Honours Degree or of Level 6(SLQF) with a minimum GPA of 3.7 on a scale of 0-4, and passing the qualifying examination after a minimum period of one year with required merit acceptable to the Senate (I.II)/ Registered to follow an MPhil degree programme in a related area at SLIIT and passing the qualifying examination conducted by SLIIT after a minimum period of one year with required merit acceptable to the Senate to upgrade the registration to the Degree programme. (I.III)', 'Rs.215,000.00', 'February/ July'),
//     createData('MSc. Architecture', 4, '6 months', 'Minimum 6 months work experience under a Chartered architect or an architecture firm. The candidates fulfilling the entry requirements for the programme will be selected through and interview process conducted by the SLIIT School of Architecture', 'Rs.280,000.00', 'February/ July'),

// ];

export const all = [
    // createData('', '', '', 'Faculty of Computing', '', '','Faculty of Computing'),
    createData('BSc. Information Technology (Specialized in Information Technology)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September','Faculty of Computing'),
    createData('BSc. Information Technology (Specialized in Computer System & Network Engineering)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT', 'Rs.240,000.00', 'February/ June/ September','Faculty of Computing'),
    createData('BSc. Information Technology (Specialized in Software ENgineering)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT. To progress from the second year to the third year of the program, a student must pass all the modules up to the second year and maintain a minimum CGPA of 2.7.', 'Rs 215,000 per semester for the first two years and Rs. 240,000 per semester for the final two years', 'February/ June/ September','Faculty of Computing'),
    createData('BSc. Information Technology (Specialized in Information System Engineering)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT.', 'Rs.215,000.00', 'February/ June/ September','Faculty of Computing'),
    createData('BSc. Information Technology (Specialized in Cyber Security)', 8, '6 months', 'Passes in three subjects (in any stream) at the G.C.E (Advanced Level) examination (Sri Lankan/London) in one and the same sitting and a pass at the Aptitude Test conducted by SLIIT. To progress from the first year to the second year of the specialization, a student must meet the minimum GPA requirement specified by the Faculty.', ' Rs 215,000 per semester for the first year and Rs. 240,000 per semester for the final three years.', 'February/ June/ September','Faculty of Computing'),
    createData('BSc. Information Technology (Specialized in Interactive Media)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination(Sri Lankan/London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT. To progress from the second year to the third year of the program, a student must pass a selection interview.', 'Rs.215,000.00', 'February/ June/ September','Faculty of Computing'),
    createData('BSc. Information Technology (Specialized in Data Science)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. Advanced Level Examination (Sri Lanka / London) in one and the same sitting, and a pass at the Aptitude Test conducted by SLIIT. To progress from the second year to the third year of the program, a student must pass all the modules up to the second year and maintain a minimum CGPA of 2.7', 'Rs 215,000 per semester for the first two years and Rs. 240,000 per semester for the final two years', 'February/ June/ September','Faculty of Computing'),

    // createData('', '', '', 'Faculty of Engineering', '', '', 'Faculty of Engineering'),
    createData('BSc. Engineering (Hons) in Civil Engineering', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.330,000.00', 'February/ September', 'Faculty of Engineering'),
    createData('BSc. Engineering (Hons) in Electrical & Electronic Engineering', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.330,000.00', 'February/ September', 'Faculty of Engineering'),
    createData('BSc. Engineering (Hons) in Mechanical Engineering', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ September', 'Faculty of Engineering'),
    createData('BSc. Engineering (Hons) in Mechanical Engineering (Mechatronics specialization ', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.330,000.00', 'February/ September', 'Faculty of Engineering'),
    createData('BSc. Engineering (Hons) in Material Engineering', 8, '6 months', 'Minimum of two “C” passes and one “S” pass in GCE Advanced Level (Local) in the Physical Science Stream (Combined Mathematics, Physics and Chemistry) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT OR Minimum of two “B” passes and one “C” pass in GCE Advanced Level (Cambridge or Edexcel) covering Combined Mathematics, Physics and Chemistry in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.330,000.00', 'February/ September', 'Faculty of Engineering'),
    createData('BSc. (Hons) Degree in Quantity Surveying', 6, '6 months', 'Minimum of 3 "S" passes in Physical Science stream & a "C" pass for O/L English.Or Minimum of 3 "S" passes in Biology/Commerce/ Engineering Technology Streams & a “B” pass for O/L Mathematics & a “C” pass for O/L English. Cambridge/Edexcel A/Ls : Minimum of 3 "D" passes in Mathematics stream (Subjects equivalent to local Physical Science Stream) & a "C" pass for O/L English. Or Minimum of 3 "D" passes in Biology/Commerce Streams & a “B” pass for O/L Mathematics & a “C” pass for O/L English.', 'Rs.215,000.00', 'February/ September', 'Faculty of Engineering'),

    // createData('', '', '', 'Faculty of Business', '', '', 'Faculty of Business'),
    createData('BBA (Hons) Specializing in Accounting & Finance', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September', 'Faculty of Business'),
    createData('BBA (Hons) Specializing in Business Analytics', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', ' Rs 215,000 per semester for the first two years and Rs. 240,000 per semester for the final two years.', 'February/ June/ September', 'Faculty of Business'),
    createData('BBA (Hons) Specializing in Human Capital Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September', 'Faculty of Business'),
    createData('BBA (Hons) Specializing in Marketing Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September', 'Faculty of Business'),
    createData('BBA (Hons) Specializing in Logistic & Supply Chain Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September', 'Faculty of Business'),
    createData('BBA (Hons) Specializing in Business Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September', 'Faculty of Business'),
    createData('BBA (Hons) Specializing in Management Information Systems', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September', 'Faculty of Business'),
    createData('BBA (Hons) Specializing in Quality Management', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September', 'Faculty of Business'),
    createData('Bachelor of Business Administration (Hons)', 8, '6 months', 'Passes in three subjects (in any subject stream) at the G.C.E. (Advanced Level) Examination (Sri Lanka / London) in one and the same sitting and a pass at the Aptitude test conducted by SLIIT', 'Rs.215,000.00', 'February/ June/ September', 'Faculty of Business'),

    // createData('', '', '', 'Faculty of Humanities & Sciences', '', '', 'Faculty of Humanities & Sciences'),
    createData('Higher Diploma in Nursing', 6, '6 months', 'Passes in three subjects at the G.C.E. Advanced Level examinations (Edexcel / Cambridge / Local or equivalent) obtained at one and the same sitting in the Science stream. A pass in the aptitude test conducted by SLIIT. Successful passing at an Interview conducted by a Board of Academic Panel', 'Rs.215,000.00', 'February/ September', 'Faculty of Humanities & Sciences'),
    createData('B.Ed (Hons) in Biological Sciences', 8, '6 months', 'Pass in three subjects at the G.C.E Advanced Level examinations (Local or London or equivalent) obtained at one and the same sitting in the Science stream and a pass in the aptitude test conducted by the Institute.', 'Rs.170,000.00', 'February/ September', 'Faculty of Humanities & Sciences'),
    createData('B.Ed (Hons) in English', 8, '6 months', 'Minimum of three (03) “S’’ passes in any subject stream (‘English’ should be one of the main three subjects) in one and the same sitting at the GCE (Advance Level) Examination (Sri Lanka/London) and the same sitting, and a pass at the Aptitude Test conducted by SLIIT', 'Rs.170,000.00', 'February/ September', 'Faculty of Humanities & Sciences'),
    createData('B.Ed (Hons) in Physical Sciences', 8, '6 months', 'Passes in three subjects including Mathematics (Combined Mathematics or Higher Mathematics) and Physics at G.C.E (Advanced Level) Examination in one and the same sitting and a pass in the Aptitude Test conducted by the Institute.', 'Rs.170,000.00', 'February/ September', 'Faculty of Humanities & Sciences'),
    createData('B.Ed (Hons) in Biotechnology', 8, '6 months', '- Three ‘S’ passes at G.C.E. Advanced Level examinations covering Biology & Chemistry OR three ‘D’ passes at Edexcel or Cambridge Advanced Level examinations covering Biology & Chemistry with obtained at one and the same sitting in the Science stream.- A Pass in the Aptitude Test conducted by the Institute.', 'Rs.250,000.00', 'February/ September', 'Faculty of Humanities & Sciences'),
    createData('B.Ed (Hons) in Financial Mathematics and Applied Statistics', 8, '6 months', ' Passes in three subjects in Physical Science stream at local G.C.E. Advanced Level Examination or equivalent qualification of London/Cambridge A/L examination in one and the same sitting and a pass in the Aptitude Test conducted by the Institute.', 'Rs.215,000.00', 'February/ September', 'Faculty of Humanities & Sciences'),
    createData('LLB (Hons) Law', 6, '6 months', '2 Credit Passes and 1 simple pass in any subject stream at GCE (Advanced Level) Examination, Sri Lanka or London in one and the same sitting with a Credit (C) pass for English at the GCE (Ordinary Level) examination and Pass at the aptitude test conducted by SLIIT and the interview conducted by the School of Law, SLIIT', 'Rs.215,000.00', 'February/ September', 'Faculty of Humanities & Sciences'),
    createData('BSc (Hons) Psychology', 6, '6 months', 'Eligibility for the programme are as follows: GCE Advance Level (Local) - 3 passes in any stream. GCE Advance Level (Edexcel / Cambridge) - 3 D passes in any stream. Final Year Entry to the BSc (Hons) Psychology Higher Diploma/Higher national Diploma in Psychology', 'Rs.215,000.00', 'February/ July', 'Faculty of Humanities & Sciences'),
    createData('BSc (Hons) Nursing (International)', 4, '6 months', 'Eligibility for the programme are as follows: Criteria for admission Overseas qualifications Candidates must be able to satisfy the programme team that they meet the entry requirements of the programme: Students must demonstrate a proficiency in English with either a credit pass for English at the GCE (Ordinary level) examination - OR the standard equivalent to IELTS 6. The candidate must be employed as a nurse and must have at least 1 year\'s post-registration experience and a Sri Lankan Diploma of nursing.', 'Rs.215,000.00', 'February/ July', 'Faculty of Humanities & Sciences'),

    // createData('', '', '', 'Faculty of Architecture', '', '', 'Faculty of Architecture'),
    createData('BSc. (Hons) in Architecture', 6, '6 months', 'GCE Advanced Level (Local) - 3 passes in any stream. (Preferably in the Biology, Mathematics or Engineering Technology) GCE Advanced Level ((Ed-excel/Cambridge) – 3 passes and meet the required 5 points Compulsory “C”passes in Mathematics and English at the GCE Ordinary Level (Local / London) Successful candidates will be selected through an aptitude test (followed by an interview if required) conducted by the SLIIT School of Architecture at the SLIIT Malabe Campus.', 'Rs.215,000.00', 'February/ June', 'Faculty of Architecture'),
    createData('BA (Hons) Interior Design', 6, '6 months', 'GCE advanced level examination (local) or London advanced level examinations 3 passes in any stream. Lateral Entry– Foundation Course (1 Year) approved by LJMU with GCE Ordinary Level examinations (local) 6 passes in any stream with minimum C passes for both Math\'s and English Successful candidates will be selected through an aptitude test (followed by an interview if required) conducted by the School of Architecture at SLIIT.', 'Rs.240,000.00', 'February/ June', 'Faculty of Architecture'),

    // createData('', '', '', 'Faculty of Hospitality & Culinary', '', '', 'Faculty of Hospitality & Culinary'),
    createData('Advance Diploma in Hospitality Management', 4, '6 months', 'Sri Lankan students: 5 Ordinary Level Passes including English language, International Students: 5 passes in the 10th standard including English language.', '<a href="https://www.cahm.lk/programmes/degree-diploma-programmes/hospitality-management/">Fees Details</a>', 'February/ June/ September', 'Faculty of Hospitality & Culinary'),
    createData('Commercial Cookery', 3, '6 months', 'Sri Lankan students: 5 Ordinary Level Passes including English language, International Students: 5 passes in the 10th standard including English language.', '<a href="https://www.cahm.lk/programmes/degree-diploma-programmes/commercial-cookery/">Fees Details</a>', 'August/ December', 'Faculty of Hospitality & Culinary'),
    createData('Certificate in Patisserie', 4, '6 months', '5 Passes in O/Level (Local/London/Cambridge)including English', 'COntact SLIIT', 'February/ July', 'Faculty of Hospitality & Culinary'),
    createData('Advance Diploma in Travel and Tourism Management', 3, '6 months', '5 Passes in O/Level (Local/London/Cambridge)including English', 'Contact SLIIT', 'February/ July', 'Faculty of Hospitality & Culinary'),
    createData('Diploma in Event Management', 8, '6 months', 'Sri Lankan students: 5 Ordinary Level Passes including English language, International Students: 5 passes in the 10th standard including English language.', '<a href="https://www.cahm.lk/programmes/event-management/">Fees Details</a>', 'August/ December', 'Faculty of Hospitality & Culinary'),

    // createData('', '', '', 'Faculty of Graduate Studies & Research', '', '', 'Faculty of Graduate Studies & Research'),
    createData('Postgraduate Diploma in Education', 4, '4.5 months', ' To have degree obtained from a recognized university or a degree awarding institution recognized by the Ministry of Education or To have a Certificate of National Vocational Qualification level 7 ', 'Rs.110,000.00', 'December', 'Faculty of Graduate Studies & Research'),
    createData('MSc in Information Technology', 4, '6 months', 'A Bachelor of Science Honors Degree in Information Technology of the Sri Lanka Institute of Information Technology (SLIIT)./ A Bachelor of Science Honors Degree in Computer Science/ Information Technology/Software Engineering from a recognized University in Sri Lanka./ A Bachelor’s degree in a relevant field from a recognized University/Institute as approved by the SLIIT with relevant experience, where necessary / Membership of a recognized professional institute in a relevant field as approved by SLIIT with relevant experience, where necessary.', 'Rs.375,000.00', 'June', 'Faculty of Graduate Studies & Research'),
    createData('MSc in information Management', 4, '6 months', 'A Bachelor of Science Degree in any field from a recognized University in Sri Lanka/ Any Bachelor’s Degree in a relevant field from a recognized University or institute as approved by SLIIT/ Membership of a recognized professional institute in a relevant field as approved by the SLIIT with relevant field experience, where necessary. And One year working experience at Managerial Level', 'Rs.375,000.00', 'June', 'Faculty of Graduate Studies & Research'),
    createData('MSc in Information Systems', 4, '6 months', 'A Bachelor of Science Honors Degree in Information Technology of the SLIIT./ A Bachelor of Science Honors Degree in Computer Science/ Information Technology/Software Engineering from a recognized University in Sri Lanka./ A Bachelor’s degree in a relevant field from a recognized University/Institute as approved by the SLIIT with relevant experience, where necessary/ Membership of a recognized professional institute in a relevant field as approved by SLIIT with relevant experience, where necessary', 'Rs.375,000.00', 'June', 'Faculty of Graduate Studies & Research'),
    createData('MSc in Information Technology - Cyber Security', 4, '6 months', 'A Bachelor of Science Honors Degree in Information Technology of the SLIIT/ A Bachelor of Science Honors Degree in Computer Science/ Information Technology/Software Engineering from a recognized University in Sri Lanka/ A Bachelor’s degree in a relevant field from a recognized University/Institute as approved by the SLIIT with relevant experience, where necessary./ Membership of a recognized professional institute in a relevant field as approved by SLIIT with relevant experience, where necessary', 'Rs.395,000.00', 'June', 'Faculty of Graduate Studies & Research'),
    createData('MSc in Information technology - Enterprise Application Development', 4, '6 months', 'A Bachelor of Science Honors Degree in Information Technology of the SLIIT/ A Bachelor of Science Honors Degree in Computer Science/ Information Technology/Software Engineering from a recognized University in Sri Lanka/ A Bachelor’s degree in a relevant field from a recognized University/Institute as approved by the SLIIT with relevant experience, where necessary./ Membership of a recognized professional institute in a relevant field as approved by SLIIT with relevant experience, where necessary', 'Rs.395,000.00', 'June', 'Faculty of Graduate Studies & Research'),
    createData('Master of Business Administration', 4, '6 months', 'The applicants with a Bachelor’s Degree in Business Administration or related area from a recognized university are eligible to apply for the course. Those with a Bachelor’s Degree in other subject areas need to have one year’s post qualifying experience. Applicants with professional qualifications and two year’s post-qualifying experience approved by SLIIT are also eligible to apply.', 'Rs.500,000.00', 'June', 'Faculty of Graduate Studies & Research'),
    createData('Master of Philosophy (MPhil)', '4/ 6', '6 months', 'A Bachelor’s Honours Degree of SLQF level 6 with a minimum of 15 credits in a related field/ A Bachelor’s degree of SLQF level 5 with a minimum GPA of 3 on a scale of 0-4 and after the successful completion of 30 credits equivalent to SLQF 6 in a related field./ A qualification of SLQF level 7, i.e. a Postgraduate Certificate or above in a related field./ Completion of NVQF level 7 with a minimum GPA of 3 in a scale of 0-4 and the successful completion of 30 credit equivalent to SLQF level 6 or above in a related field as approved by the institute', 'Rs.200,000.00', 'All year', 'Faculty of Graduate Studies & Research'),
    createData('Doctor of Philosophy (PhD) ', '6/ 10', '6 months', 'A Master of Philosophy Degree from a recognized institution acceptable to the Senate (I.I)/ A Bachelor’s Honours Degree or of Level 6(SLQF) with a minimum GPA of 3.7 on a scale of 0-4, and passing the qualifying examination after a minimum period of one year with required merit acceptable to the Senate (I.II)/ Registered to follow an MPhil degree programme in a related area at SLIIT and passing the qualifying examination conducted by SLIIT after a minimum period of one year with required merit acceptable to the Senate to upgrade the registration to the Degree programme. (I.III)', 'Rs.215,000.00', 'February/ July', 'Faculty of Graduate Studies & Research'),
    createData('MSc. Architecture', 4, '6 months', 'Minimum 6 months work experience under a Chartered architect or an architecture firm. The candidates fulfilling the entry requirements for the programme will be selected through and interview process conducted by the SLIIT School of Architecture', 'Rs.280,000.00', 'February/ July', 'Faculty of Graduate Studies & Research'),

]

