function createData(name, no, start,route, note, contact) {
    return { name, no, start, route, note,contact };
}

export const row = [
    createData('Kolpitiy - Malabe', 'NC - 3978','07.20 a.m From Marine Drive Kolpity Railway Station, 05.30 p.m From SLIIT','Marine Drive Kolpity Railway Station - Senanayake Junction - Rajagiriya Flyover - Battaramulla - Koswatta - Malabe Junction - SLIIT','Average arrival time of the student shuttle to SLIIT Malabe Campus is 8.15 a. m. Arrival time and the duration of travel are based on average traffic conditions and it may vary due to actual traffic conditions on the day','Mr. Mindika - 0771692215'),
    createData('Ja Ela - Malabe', 'NC - 3928','06.30 a.m From Ja Ela Railway Station, 05.30 p.m From SLIIT','Ja Ela Railway Station - Kapuwaththa - Kandana - Mahabage - Ragama - Kadawatha - Mawaramandiya - Galwala Junction - Power House - Siyabalape - Kaduwela Junction - SLIIT','Average arrival time of the student shuttle to SLIIT Malabe Campus is 8.15 a. m. Arrival time and the duration of travel are based on average traffic conditions and it may vary due to actual traffic conditions on the day','Mr. Premarathna - 0728542443'),
    createData('Panadura - Malabe', 'ND - 0752','06.05 a.m From Near Rankoth Viharaya Temple - Panadura, 05.30 p.m From SLIIT','Panadura - Moratuwa - Katubedda - Dehiwala (William Junction) - Kohuwala - Nugegoda - Pitakotte - Thalawathugoda - Hokandara - Arangala Junction - Malabe Junction - SLIIT','Average arrival time of the student shuttle to SLIIT Malabe Campus is 8.15 a. m. Arrival time and the duration of travel are based on average traffic conditions and it may vary due to actual traffic conditions on the day','Mr. Chaminda - 0758208900'),
    createData('Negombo - Malabe', 'ND - 3093','	06.30 a.m From Negombo Bus Stand, 05.30 p.m From SLIIT','Negombo Bus Stand - Koppara Junction - Katunayake 18th Mile Post - Highway - Thorana Junction - Kelaniya Temple - Bandarawaththa - Kaduwela Junction - SLIIT','Average arrival time of the student shuttle to SLIIT Malabe Campus is 8.15 a. m. Arrival time and the duration of travel are based on average traffic conditions and it may vary due to actual traffic conditions on the day','Mr. Kasun - 0742134934'),
]